export const UMKMData = [
  {
    id: 1,
    namaToko: "Arfi Sagon",
    tipeData: "Merk",
    namaPemilik: "Anik Rusmawati",
    alamat: "Rt 03 Rw 04 dusun Jatinom",
    foto: "/assets/images/umkm/sagon-arfi.jpg",
    kontak: "085746304720",
    desc:"UMKM ini menyediakan aneka ragam olahan kelapa berupa Sagon Kelapa. UMKM ini memiliki banyak varian atau rasa untuk produk Sagon Kelapanya yang tentunya rasanya enak dan tidak bikin eneg karena memiliki banyak varian rasa."
  },
  {
    id: 2,
    namaToko: "Arfi Sagon",
    namaProduk: "Sagon Kelapa",
    tipeData: "Produk",
    namaPemilik: "Anik Rusmawati",
    alamat: "Rt 03 Rw 04 dusun Jatinom",
    foto: "/assets/images/umkm/sagon-arfi1.jpg",
    kontak: "085746304720",
  },
  {
    id: 3,
    namaToko: "Arfi Sagon",
    namaProduk: "Sagon Kelapa",
    tipeData: "Produk",
    namaPemilik: "Anik Rusmawati",
    alamat: "Rt 03 Rw 04 dusun Jatinom",
    foto: "/assets/images/umkm/sagon-arfi2.jpg",
    kontak: "085746304720",
  },
  {
    id: 4,
    namaToko: "Moo",
    tipeData: "Merk",
    namaPemilik: "Peni",
    alamat: "Rw 03 dusun Jatinom",
    foto: "/assets/images/umkm/yogurt-moo.jpg",
    kontak: "082245492473",
    desc:"UMKM ini menyediakan berbagai olahan susu baik itu makanan maupun minuman dengan bahan-bahan yang segar dan rasa yang lezat tentunya. UMKM ini mempunyai produk makanan atau snack seperti Stik Susu dan Permen Susu serta minuman segar berupa susu dan snack ",
  },
  {
    id: 5,
    namaToko: "Moo",
    namaProduk: "Yoghurt Aneka Rasa",
    tipeData: "Produk",
    namaPemilik: "Peni",
    alamat: "Rw 03 dusun Jatinom",
    foto: "/assets/images/umkm/yogurt-moo.jpg",
    kontak: "082245492473",
  },
  {
    id: 6,
    namaToko: "Moo",
    namaProduk: "Susu Pasteurisasi Rasa Coklat",
    tipeData: "Produk",
    namaPemilik: "Peni",
    alamat: "Rw 03 dusun Jatinom",
    foto: "/assets/images/umkm/susucoklat-moo.jpg",
    kontak: "082245492473",
  },
  {
    id: 7,
    namaToko: "Moo",
    namaProduk: "Stik Susu",
    tipeData: "Produk",
    namaPemilik: "Peni",
    alamat: "Rw 03 dusun Jatinom",
    foto: "/assets/images/umkm/stik-moo.jpg",
    kontak: "082245492473",
  },
  {
    id: 8,
    namaToko: "Moo",
    namaProduk: "Permen Susu",
    tipeData: "Produk",
    namaPemilik: "Peni",
    alamat: "Rw 03 dusun Jatinom",
    foto: "/assets/images/umkm/permen-moo.jpg",
    kontak: "082245492473",
  },
  {
    id: 9,
    namaToko: "Warung Mak Ti",
    tipeData: "Merk",
    namaPemilik: "Warung Mak Ti",
    alamat: "Jl. Mawar, RT.03/RW.03, Nglaos, Jatinom",
    foto: "/assets/images/umkm/makti.jpg",
    kontak: "085733345896",
    desc: "Nama warung Mak Ti sudah tak asing bagi pecinta kuliner di Blitar. Lokasinya berada di Jalan Mawar, RT 03/RW 03, Jatinom, Kota Blitar da buka pukul 06.00 hingga 08.00 WIB. Warung ini menyediakan aneka kuliner ikan air tawar seperti bader, wader ucena dan lain-lain Terlebih Anda cukup merogoh kecok Bn 15",
  },
];
